### ISSUE TITLE
Form layout not correct on mobile Safari.

### ISSUE THREAD

**Issue by hifall** [vue-bulma/vue-admin#149] opened 2017-02-11 12:56 UTC
Hi

I am having some layout issue on the form page on iPhone 5S/Safari. Please check the image below:

![img_3076](https://cloud.githubusercontent.com/assets/5734293/22853870/dc86ab40-f09b-11e6-816d-43b331f67eea.PNG)

To repro it, simply navigate to the form page in mobile iPhone 5S/Safari.

**Comment by luventa** [comment] 2017-02-11 14:28
Yes there are some layout issues in Form demo.
Most of them are caused by emelemts with undefined width.
I will try to fix these later.
Thanks for reporting this!

**Comment by luventa** [comment] 2017-02-22 06:24
fixed in [dbb2157](https://github.com/vue-bulma/vue-admin/commit/dbb2157fc311f3dd38cedb2f684d30ab460570c5)

**Closed** 2017-02-23 04:33 UTC
